POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "video 01",
    "description": "esse é o primeiro videos",
    "duration": 180
}

###

GET http://localhost:3333/videos
